### ISSUE TITLE
触控板问题

### ISSUE THREAD

**Issue by liuyishengalan** [yqsas/Hackintosh-T480s#1]
我是Thinkpad p52，触摸板也是elan ps2，但我用了你的kext之后，触摸板只能显示控制面板，但无法工作。你看看，能不能发一下完整的驱动方法，想参考一下。对了，x1c的黑苹果qq群号码能留一下吗，想加一下

**Comment by yqsas** [comment]
不确定p52是否通用。
1.小红点在BIOS禁用了吗？
2.可以下载原版ApplePS2SmartTouchPad.kext尝试，这里的是有一点修改的。

thinkPad X1 Carbon黑果群聊号码：678377747
