### ISSUE TITLE
小红点与触摸板并存问题已经有国外大牛解决了

### ISSUE THREAD

**Issue by yszhangyh** [yqsas/Hackintosh-T480s#4]
请参考这个项目，有安装说明：https://github.com/leo-labs/VoodooSMBus, 安装完后有更完美的手势操作，还可以在设置中心定制手势，但还存在唯一问题：

> 拖放文件时不能切换手指

用一个手指在拖动文件或选择文本时，当这个手指到达了触摸板边缘且还没有把文件拖动到目的地时，我用另外一个手指按住触摸板中央，然后抬起原手指继续完成拖动，此时，被拖动的文件就被释放了，相当于取消了拖动。

虽然说有这个问题存在，但有更完美的手势操作，建议你还是更新一下吧，因为本人英文水平有限，不方便与原作者沟通，若你能联系他解决此bug，t480s上运行黑苹果基本上就完美了。

**Comment by yqsas** [comment]
好的，有时间就更新
