### ISSUE TITLE
Catalina 10.15.3 内置摄像头问题

### ISSUE THREAD

**Issue by yszhangyh** [yqsas/Hackintosh-T480s#6]
Catalina 10.15.3内置摄像头不工作，Face Time提示无摄像头可用

**Comment by yqsas** [comment]
我实际测试没有问题，FaceTime和其他摄像软件工作正常。

建议检查：

- 驱动：kexts/Other/UV2FaceTimeHD.kext
- 系统报告/硬件/摄像头 是否有ID
- 使用其他摄像视频软件确认问题

**Comment by yszhangyh** [comment]
删除UV2FaceTimeHD.kext驱动后FaceTime和其他软件都能正常使用了
