### ISSUE TITLE
装机卡在第十三分钟，可能是驱动问题

### ISSUE THREAD

**Issue by wangyu6** [yqsas/Hackintosh-T480s#7]
嗯，我将4G模块改成硬盘，双硬盘模式 （pm981a+Lexar 256g），尝试将系统装到Lexar 那个固态)里(没有动pm981），无法安装。总是卡在第十三分钟。请问是驱动原因吗？
如果要换硬盘，除了sm961 ，将pm981a换成sn550可以吗?
非常感谢
（16g+i5 8250+pm981 1t+mx150）

**Comment by yqsas** [comment]
系统是最新的15.4吗？如果硬件没其他变化的情况下，建议你安装过程中先拔掉pm981，这个在早期是装机卡死重要因素。驱动里面经过很多小伙伴验证，应该是没有问题的，我也都是实测通过再更新出来。
sn550手上没有，未验证，你可以尝试。

**Comment by wangyu6** [comment]
非常感谢耐心解答
实测sn550支持黑苹果，不过我是用装10.15版本 在神舟战神 （主板为N8XXEP6,蓝天模具//据说 )安装成功的  。
原来t480s放弃黑苹果了。。。

**Comment by xiaotianxt** [comment]
> 非常感谢耐心解答
> 实测sn550支持黑苹果，不过我是用装10.15版本 在神舟战神 （主板为N8XXEP6,蓝天模具//据说 )安装成功的 。
> 原来t480s放弃黑苹果了。。。

我这边T480s + SN550可以安装黑苹果，但是存在一个问题，就是触控板和小红点会突然失灵，重启之后恢复。。。。
