### ISSUE TITLE
Trackpad和Trackpoint在电脑使用一段时间后失灵

### ISSUE THREAD

**Issue by xiaotianxt** [yqsas/Hackintosh-T480s#8]
大神您好，想请教一下，我使用了您更新的VooDooSMBus驱动，ACPI按照库里的照搬，然而现在触控板在使用一段时间后会突然失灵，并不是发生在睡眠后。重启后正常，而且发现在重启黑屏前的一瞬间触控板又会重新有效。我猜测可能是驱动之间相互冲突之类的？我使用的是黑果小兵的镜像，下面附有驱动和补丁，谢谢🙏
MacOS版本：10.15.5
![image](https://user-images.githubusercontent.com/17041194/83778177-ed172180-a6bc-11ea-9952-6af8c688e2bb.png)
![image](https://user-images.githubusercontent.com/17041194/83778215-f99b7a00-a6bc-11ea-9064-781221154428.png)

**Comment by yqsas** [comment]
触控板驱动仓库地址：<https://github.com/VoodooSMBus/VoodooSMBus>，按照此仓库里的说明使用。
***
如果是一个T480s的话，可以尝试把kexts/Other/里面所有内容替换为此仓库对应内容再试。你的驱动列表有一些实际上已经不再使用的驱动，做一下清理。
其他机型不保证有效。
