### ISSUE TITLE
请问，在WWAN口额外加的建兴T11硬盘在hackintosh后还能识别吗？

### ISSUE THREAD

**Issue by zuruncai** [yqsas/Hackintosh-T480s#9]

**Comment by yqsas** [comment]
1. 据用过的人说，建兴T11可识别；
2. DW1560蓝牙稳定性比较一般，有时可用有时不可用，可以考虑其他免驱无线网卡；
3. 内存没问题，我自己也加了16G；
4. 有个缺憾是hidpi最高只能稳定到810p，再高睡眠唤醒会花屏。其他没有问题。

**Comment by Cai-Zurun** [comment]
感谢您的回答。网卡我买了个博通的BCM94352Z。我试试效果如何

**Comment by zuruncai** [comment]
> 1. 据用过的人说，建兴T11可识别；
> 2. DW1560蓝牙稳定性比较一般，有时可用有时不可用，可以考虑其他免驱无线网卡；
> 3. 内存没问题，我自己也加了16G；
> 4. 有个缺憾是hidpi最高只能稳定到810p，再高睡眠唤醒会花屏。其他没有问题。

感谢您的回答。网卡我买了个博通的BCM94352Z。我试试效果如何

**Comment by rhkjyn** [comment]
不休眠的话，蓝牙没有问题



---原始邮件---
发件人: "zrun"<notifications@github.com&gt;
发送时间: 2020年7月11日(周六) 下午2:42
收件人: "yqsas/Hackintosh-T480s"<Hackintosh-T480s@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [yqsas/Hackintosh-T480s] 请问，在WWAN口额外加的建兴T11硬盘在hackintosh后还能识别吗？ (#9)




   
据用过的人说，建兴T11可识别； 

DW1560蓝牙稳定性比较一般，有时可用有时不可用，可以考虑其他免驱无线网卡； 

内存没问题，我自己也加了16G； 

有个缺憾是hidpi最高只能稳定到810p，再高睡眠唤醒会花屏。其他没有问题。 
  
感谢您的回答。网卡我买了个博通的BCM94352Z。我试试效果如何
